greetings/urls.py
from django.urls import path

from . import views

app_name = 'greetings'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('greetings/', include('greetings.urls')),
    path('admin/', admin.site.urls),
]

greetings/models.py
from django.db import models

# Create your models here.

class Greeting(models.Model):
    message = models.CharField(max_length=200)
    related_greetings = models.ManyToManyField('self', through="GreetingPair")

class GreetingPair(models.Model):
    initial_greeting = models.ForeignKey(Greeting, on_delete=models.SET_NULL, related_name="initial_greeting", blank=True, null=True)
    responding_greeting = models.ForeignKey(Greeting, on_delete=models.SET_NULL, related_name="responding_greeting", blank=True, null=True)
    comment = models.CharField(max_length=200)

greetings/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Greeting


class IndexView(generic.ListView):
    template_name = 'greetings/index.html'
    context_object_name = 'greeting_list'
    def get_queryset(self):
        """Return the all greetings."""
        return Greeting.objects.all()

class CreateView(generic.edit.CreateView):
    template_name = 'greetings/create.html'
    model = Greeting
    fields = ['message', 'related_greetings']
    success_url = reverse_lazy('greetings:index') # more robust than hardcoding to /greetings/; directs user to index view after creating a greeting

class UpdateView(generic.edit.UpdateView):
    template_name = 'greetings/update.html'
    model = Greeting
    fields = ['message', 'related_greetings']
    success_url = reverse_lazy('greetings:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'greetings/delete.html' # override default of greetings/greeting_confirm_delete.html
    model = Greeting
    success_url = reverse_lazy('greetings:index')

greetings/templates/greetings/create.html
<form method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save">
</form>

greetings/templates/greetings/delete.html
<form method="post">{% csrf_token %}
	<p>Are you sure you want to delete "{{ object.message }}"?</p>
	<input type="submit" value="Confirm">
</form>

greetings/templates/greetings/index.html
{% if greeting_list %}
    <ul>
    {% for greeting in greeting_list %}
        <li>{{ greeting.message }}</li>
	<span><a href="{% url 'greetings:update' greeting.id %}">edit</a></span>
	<span><a href="{% url 'greetings:delete' greeting.id %}">delete</a></span>
    {% endfor %}
    </ul>
{% else %}
    <p>No greetings are available.</p>
{% endif %}
<a href="{% url 'greetings:create' %}">Create a New Greeting</a>

greetings/templates/greetings/update.html
<form method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update">
	<a href="{% url 'greetings:delete' greeting.id %}">delete</a>
</form>